CREATE TABLE known_turtles(name VARCHAR(20), species VARCHAR(20), age INT, location VARCHAR(20));

INSERT INTO known_turtles VALUES ('Donatello', 'Teenage Mutant Ninja',  15, 'Sewers')
INSERT INTO known_turtles VALUES ('Leonardo', 'Teenage Mutant Ninja',  15, 'Sewers')
INSERT INTO known_turtles VALUES ('Raphael', 'Teenage Mutant Ninja',  15, 'Sewers')
INSERT INTO known_turtles VALUES ('Michelangelo', 'Teenage Mutant Ninja',  15, 'Sewers')
INSERT INTO known_turtles VALUES ('Brian', 'Snapping', 2, 'New York')
INSERT INTO known_turtles VALUES ('Joe', 'Snapping', 5, 'Boston')
INSERT INTO known_turtles VALUES ('Walter', 'Diamondback Terrapin', 20, 'Boston')
INSERT INTO known_turtles VALUES ('Edgar', 'Diamondback Terrapin', 10, 'New York')
INSERT INTO known_turtles VALUES ('Justin', 'Diamondback Terrapin', 12, 'San Diego')
INSERT INTO known_turtles VALUES ('Roxy', 'Diamondback Terrapin', 11, 'San Diego')
INSERT INTO known_turtles VALUES ('Emma', 'Red Ear', 18, 'New York')
INSERT INTO known_turtles VALUES ('Stealth', 'Red Ear', 22, 'Boston')
INSERT INTO known_turtles VALUES ('Georgie', 'Red Ear', 6, 'Boston')
INSERT INTO known_turtles VALUES ('Buster', 'Yellow Bellied', 8, 'New York')
INSERT INTO known_turtles VALUES ('Margie', 'Yellow Bellied', 9, 'New York')
INSERT INTO known_turtles VALUES ('Peter', 'Yellow Bellied', 5, 'Boston')
INSERT INTO known_turtles VALUES ('Wendy', 'Yellow Bellied', 13, 'San Diego')

